pipeline 
{
    agent any
    stages 
    {
        stage('Build docker image')
        {
            steps
            {
		echo "-----Start build docker image-----"
		sh "ls -la"
		sh "tree"

            }

        }
    }
}
