pipeline 
{
    agent any
    stages 
    {
        stage('Build docker image')
        {
            steps
            {
		echo "-----Start build docker image-----"
		dir('content')
		{
			sh "docker build -t webviajenkins:v1 ."
			sh "docker images"
		}

            }

        }
    }
}
